model_params:
  name: 'MINEDisentangleVAE'
  in_channels: 3
  latent_dim: 128
  num_factors: 10
  factor_dim: 32
  attention_dim: 128
  mine_hidden_dim: 128
  disentanglement_weight: 1.0
  attention_reg_weight: 0.1
  entropy_reg_weight: 0.05

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.001
  weight_decay: 0.0001
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 150
  gradient_clip_val: 1.0

logging_params:
  save_dir: "logs/"
  name: "MINEDisentangleVAE" 