model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 64

data_params:
  data_path: "Data/"
  dataset_name: "dsprites"
  train_batch_size: 1
  val_batch_size: 1
  patch_size: 64
  num_workers: 0

exp_params:
  LR: 0.001
  weight_decay: 0.0001
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "cpu"  # CPU test
  devices: 1
  max_epochs: 1
  log_every_n_steps: 10

logging_params:
  save_dir: "logs/"
  name: "VanillaCPUTest" 